version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws s3 cp ./deployment_package.zip s3://destini-estimator/codebuild_package/
      - aws lambda update-function-code --function-name estimate_tracker --s3-bucket destini-estimator --s3-key codebuild_package/deployment_package.zip
      - echo "DONE!!"
